api = "0.8"

[buildpack]
  id = "com.anynines.buildpacks.rvm-rails-assets"
  name = "RVM Buildpack for rails assets"
  homepage = "https://github.com/avarteqgmbh/rvm-rails-assets"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"
