api = "0.4"

[buildpack]
  id = "com.anynines.buildpacks.rvm-rails-assets"
  name = "RVM Buildpack for rails assets"
  version = "0.0.1"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
